name: Deploy
on: { release: { types: [ released ] } }
jobs:
  deploy-components:
    runs-on: ubuntu-latest
    steps:
      - uses: cluebotng/ci-update-component-ref@main
        with:
          tool: '*'
          repository: 'https://github.com/cluebotng/fileserver.git'
          ref: '${{ github.ref }}'
          gh_app_key: '${{ secrets.CI_COMPONENT_CONFIGS_APP_KEY }}'
